#cloud-config

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

groups:
  - docker

runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce=5:19.03.10~3-0~ubuntu-bionic docker-ce-cli=5:19.03.10~3-0~ubuntu-bionic containerd.io
  - systemctl start docker
  - systemctl enable docker
