name: publish-artifact
on: 
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  zip-files-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v1
        name: upload SCALABLE artifact
        with:
          name: scalable
          path: ${{ github.workspace }}/offerings/scalable/
      - uses: actions/upload-artifact@v1
        name: upload SINGLE WIN VM artifact
        with:
          name: singel_win_vm
          path: ${{ github.workspace }}/offerings/single-win-vm/deployment/


     