name: Create Archive
on:
  push:
    branches: [ dbr_#10 ]
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: infrastructure/
          recursive: false
          dest: ubuntu.zip
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/ubuntu.zip